(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,q=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};const ba=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){const d=a.length,e="string"===typeof a?a.split(""):a;for(let c=0;c<d;c++)if(c in e&&!b.call(void 0,e[c],c,a))return!1;return!0};var ca={},r=null,da=function(a){var b;void 0===b&&(b=0);if(!r){r={};for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),e=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var f=d.concat(e[c].split(""));ca[c]=f;for(var h=0;h<f.length;h++){var g=f[h];void 0===r[g]&&(r[g]=h)}}}b=ca[b];d=Array(Math.floor(a.length/3));e=b[64]||"";for(c=f=0;f<a.length-2;f+=3){var l=a[f],m=a[f+1];g=a[f+2];h=b[l>>2];l=b[(l&3)<<4|m>>4];m=b[(m&15)<<2|g>>6];g=b[g&63];d[c++]=""+h+l+m+g}h=0;g=e;switch(a.length-
f){case 2:h=a[f+1],g=b[(h&15)<<2]||e;case 1:a=a[f],d[c]=""+b[a>>2]+b[(a&3)<<4|h>>4]+g+e}return d.join("")};var ea="undefined"!==typeof Uint8Array,fa={};let ha;var t=class{constructor(a){if(fa!==fa)throw Error("illegal external caller");this.B=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}};const u="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function v(a,b){Object.isFrozen(a)||(u?a[u]|=b:void 0!==a.j?a.j|=b:Object.defineProperties(a,{j:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function ia(a,b){Object.isExtensible(a)&&(u?a[u]&&(a[u]&=~b):void 0!==a.j&&(a.j&=~b))}function w(a){let b;u?b=a[u]:b=a.j;return null==b?0:b}
function x(a,b){u?a[u]=b:void 0!==a.j?a.j=b:Object.defineProperties(a,{j:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function y(a){v(a,1);return a}function ja(a){v(a,17);return a}function z(a){return a?!!(w(a)&2):!1}function ka(a){v(a,16);return a}function A(a){if(!Array.isArray(a))throw Error("cannot mark non-array as shared mutably");ia(a,16)};var B={};function C(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let la;var D=Object.freeze(y([])),F=function(a){if(z(a.g))throw Error("Cannot mutate an immutable Message");};function ma(a,b,d=!1){if(Array.isArray(a))return new b(d?ka(a):a)};function na(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(ea&&null!=a&&a instanceof Uint8Array)return da(a);if(a instanceof t){const b=a.B;return null==b?"":"string"===typeof b?b:a.B=da(b)}}}return a};function oa(a,b,d,e){if(null!=a){if(Array.isArray(a))a=pa(a,b,d,void 0!==e);else if(C(a)){const c={};for(let f in a)c[f]=oa(a[f],b,d,e);a=c}else a=b(a,e);return a}}function pa(a,b,d,e){e=e?!!(w(a)&16):void 0;const c=Array.prototype.slice.call(a);d(a,c);for(a=0;a<c.length;a++)c[a]=oa(c[a],b,d,e);return c}function qa(a){return a.A===B?a.toJSON():na(a)}function ra(){};var G=function(a,b,d=!1){return-1===b?null:b>=a.m?a.i?a.i[b]:void 0:d&&a.i&&(d=a.i[b],null!=d)?d:a.g[b+a.l]},H=function(a,b,d,e=!1,c=!1){c||F(a);a.u&&(a.u=void 0);if(b>=a.m||e)return(a.i||(a.i=a.g[a.m+a.l]={}))[b]=d,a;void 0!==a.i&&a.m>=a.g.length?(e=a.g.length-1,c=b+a.l,c>=e?(a.g[e]=void 0,a.g[c]=d,a.g.push(a.i)):a.g[c]=d):a.g[b+a.l]=d;void 0!==a.i&&b in a.i&&delete a.i[b];return a},L=function(a,b,d){return void 0!==I(a,b,J(a,K,d))};
function sa(a,b,d){let e=G(a,b,!1);Array.isArray(e)||(e=D);const c=w(e);c&1||y(e);z(a.g)?d&1||(v(e,2),Object.freeze(e)):e===D||!(d&1&&d&2)&&c&2?(e=y(Array.prototype.slice.call(e)),H(a,b,e,!1)):!(d&2)&&c&16&&A(e);return e}function ta(a,b,d,e){F(a);d!==e?H(a,b,d):H(a,b,void 0,!1);return a}
var J=function(a,b,d){return M(a,b)===d?d:-1},M=function(a,b){let d=0;for(let e=0;e<b.length;e++){const c=b[e];null!=G(a,c)&&(0!==d&&H(a,d,void 0,!1,!0),d=c)}return d},I=function(a,b,d,e){const c=G(a,d,e);{let h=!1;var f=null==c||"object"!==typeof c||(h=Array.isArray(c))||c.A!==B?h?new b(c):void 0:c}f!==c&&null!=f&&(H(a,d,f,e,!0),v(f.g,w(a.g)&-33));return f},N=function(a,b,d){b=I(a,b,d,!1);if(null==b)return b;z(b.g)&&!z(a.g)&&(b=ua(b),H(a,d,b,!1));return b},wa=function(a,b,d=!0){var e=va;a.h||(a.h=
{});let c=a.h[b];var f=sa(a,b,2|(d?1:0));const h=!!(w(a.g)&16);var g=z(f);g=z(a.g)||g;if(!c){c=[];let m=g;for(let n=0;n<f.length;n++){var l=f[n];m=m||z(l);l=ma(l,e,h);void 0!==l&&(c.push(l),g&&v(l.g,2))}a.h[b]=c;Object.isFrozen(f)||(e=w(f)|33,x(f,m?e&-9:e|8))}d=g||d;f=z(c);d&&!f&&(Object.isFrozen(c)&&(a.h[b]=c=c.slice()),v(c,2),Object.freeze(c));!d&&f&&(a.h[b]=c=c.slice());return c},xa=function(a,b){var d=z(a.g);const e=wa(a,b,d);a=sa(a,b,3);if(d=!d&&a){if(!a)throw Error("cannot check mutability state of non-array");
d=!(w(a)&8)}if(d){for(d=0;d<e.length;d++)if((b=e[d])&&z(b.g)){b=d;var c=ua(e[d]);e[b]=c;a[d]=e[d].g}v(a,8)}return e},O=function(a,b){a=G(a,b);return null==a?"":a},P=function(a,b){a=G(a,b);a=null==a?a:!!a;return null==a?!1:a},Q=function(a,b){a=G(a,b);return null==a?0:a};function ya(a,b,d,e,c,f){if(a=a.h&&a.h[d]){e=f.o?y(a.slice()):a;F(b);if(null!=e){c=y([]);f=!1;for(a=0;a<e.length;a++)c[a]=e[a].g,f=f||z(c[a]);b.h||(b.h={});b.h[d]=e;e=c;f?ia(e,8):v(e,8)}else b.h&&(b.h[d]=void 0),c=D;H(b,d,c)}else ea&&e instanceof Uint8Array?c=e.length?new t(new Uint8Array(e)):ha||(ha=new t(null)):(Array.isArray(e)&&(c?v(e,2):e&&w(e)&1&&f.o?(c=Array.prototype.slice.call(e),x(c,(w(e)|0)&-51),e=c):A(e)),c=e),H(b,d,c)};function ua(a){if(!z(a.g))return a;var {o:b}={o:!0};b={o:b};const d=z(a.g);if(d&&!b.o)throw Error("copyRepeatedFields must be true for frozen messages");d||A(a.g);const e=new a.constructor;a.v&&(e.v=a.v.slice());const c=a.g;for(let f=0;f<c.length;f++){const h=c[f];if(f===c.length-1&&C(h))for(const g in h){const l=+g;Number.isNaN(l)?(e.i||(e.i=e.g[e.m+e.l]={}))[g]=h[g]:ya(a,e,l,h[g],d,b)}else ya(a,e,f-a.l,h,d,b)}e.u=a;return e};var S=class{constructor(a,b,d){null==a&&(a=R);R=null;var e=this.constructor.h||0,c=0<e,f=this.constructor.s,h,g=!1;if(a){if(h=!!(w(a)&16))g=w(a),x(a,g|32),g=!!(g&32)}else h=f?[f]:[],v(h,48),a=h,h=!0;c&&0<a.length&&C(a[a.length-1])&&"g"in a[a.length-1]&&(e=0);this.l=(f?0:-1)-e;this.h=void 0;this.g=a;a:{f=this.g.length;e=f-1;if(f&&(f=this.g[e],C(f))){this.i=f;b=Object.keys(f);0<b.length&&ba(b,isNaN)?this.m=Number.MAX_VALUE:this.m=e-this.l;break a}void 0!==b&&-1<b?(this.m=Math.max(b,e+1-this.l),this.i=
void 0):this.m=Number.MAX_VALUE}if(!c&&this.i&&"g"in this.i)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(d)for(c=h&&!g?ja:y,b=0;b<d.length;b++)h=d[b],(g=G(this,h))?Array.isArray(g)&&c(g):H(this,h,D,!1,!0)}toJSON(){const a=this.g;return la?a:pa(a,qa,ra)}};S.prototype.A=B;S.prototype.toString=function(){return this.g.toString()};function za(a,b){return na(b)}let R;var va=class extends S{constructor(a){super(a)}},T=[2,3,4];var U=class extends S{constructor(a){super(a)}};var V=class extends S{constructor(a){super(a)}};var Ba=class extends S{constructor(a){super(a,-1,Aa)}},Aa=[6];var Ca=class extends S{constructor(){super()}};var Da=class extends S{constructor(){super()}},Ea=[2];var Ga=class extends S{constructor(a){super(a,-1,Fa)}},Fa=[2];var Ha=class extends S{constructor(a){super(a)}};var Ia=class extends S{constructor(a){super(a)}};var Ja=class extends S{constructor(a){super(a)}};var Ka=class extends S{constructor(a){super(a)}},K=[2,3,4,5,6,7];/*

 SPDX-License-Identifier: Apache-2.0
*/
var W;var Na=function(a,b){this.s=a===La&&b||"";this.h=Ma},Ma={},La={};var Pa=class{constructor(a,b){this.h=b===Oa?a:""}toString(){return this.h+""}},Oa={};var Qa=function(){this.h=document||{cookie:""}};
Qa.prototype.set=function(a,b,d){let e,c,f,h=!1,g;"object"===typeof d&&(g=d.G,h=d.H||!1,f=d.domain||void 0,c=d.path||void 0,e=d.F);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===e&&(e=-1);this.h.cookie=a+"="+b+(f?";domain="+f:"")+(c?";path="+c:"")+(0>e?"":0==e?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*e)).toUTCString())+(h?";secure":"")+(null!=g?";samesite="+g:"")};
Qa.prototype.get=function(a,b){const d=a+"=",e=(this.h.cookie||"").split(";");for(let c=0,f;c<e.length;c++){f=aa(e[c]);if(0==f.lastIndexOf(d,0))return f.slice(d.length);if(f==a)return""}return b};class Ra{constructor(){this.s=new Qa;this.h="";this.C=a=>{a:{let p;try{var b=a.data;if(null==b||""==b)p=new Ka;else{var d=JSON.parse(b);if(!Array.isArray(d))throw Error(void 0);var e=ka(d);R=e;const E=new Ka(e);R=null;p=E}}catch(E){break a}if(L(p,Ba,4)){var c=N(p,Ba,J(p,K,4)),f=xa(c,6),h;f.length&&(h=Sa(f));f={event:O(c,1)||void 0,category:O(c,2)||void 0,action:O(c,3)||void 0,label:O(c,4)||void 0,value:Q(c,5)||void 0,nonInteraction:P(c,13)?"True":"False",additionalParams:h||void 0};if(void 0!==I(c,
V,12,!1)){var g=N(c,V,12);f.recommendations={targetPage:O(g,1),targetType:Q(g,2),targetRank:Q(g,3),targetIdenticalDescriptions:Q(g,4),targetTitleWords:Q(g,5),targetDescriptionWords:Q(g,6),experiment:O(g,7)};h="";for(var l of window.dataLayer)if("experiment"in l&&"baseIds"in l.experiment){h=l.experiment.baseIds;break}(h=Ta(h,O(g,7)))&&P(g,8)&&(f.experiment={ids:h})}else f.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,
targetDescriptionWords:void 0};if(!("experiment"in f))for(var m of window.dataLayer)if("experiment"in m&&"ids"in m.experiment&&m.experiment.ids){f.experiment={ids:m.experiment.ids};break}l=N(c,U,11);if(void 0!==I(c,U,11,!1)&&null!==l){c=Ua(l);for(var n of Object.keys(c))f[n]=c[n]}window.dataLayer.push(f)}else if(L(p,Ga,3)){c=N(p,Ga,J(p,K,3));f=xa(c,2);let E;f.length&&(E=Sa(f));f={event:"trackPageview",pageName:O(c,1),additionalParams:E||void 0,nonInteraction:P(c,3)||void 0,ratingsCount:Q(c,4)||void 0,
ratingsValue:Q(c,5)||void 0};n=N(c,U,6);if(void 0!==I(c,U,6,!1)&&null!==n){c=Ua(n);for(g of Object.keys(c))f[g]=c[g]}window.dataLayer.push(f)}else if(L(p,Ha,7))c=N(p,Ha,J(p,K,7)),window.dataLayer.push({parentContext:{referrer:O(c,2)||"",_ga_devsiteCookie:O(c,1)||""}});else if(L(p,Ia,6))c=N(p,Ia,J(p,K,6)),f=this.h,n=N(c,V,9)||new V,l=O(c,10)||void 0,c={experiment:{ids:(P(n,8)?Ta(l,O(n,7)):l)||void 0,baseIds:l||void 0},hostContext:{internalUser:O(c,1)||void 0,pageType:O(c,8)||void 0,projectName:O(c,
6)||void 0,signedIn:O(c,2)||void 0,tenant:O(c,5)||void 0,thirdPartyCookieAccepted:f.length?"True":"False"},language:{machineTranslated:O(c,7)||void 0,requested:O(c,3)||void 0,served:O(c,4)||void 0},recommendations:{sourcePage:O(n,1),sourceType:Q(n,2),sourceRank:Q(n,3),sourceIdenticalDescriptions:Q(n,4),sourceTitleWords:Q(n,5),sourceDescriptionWords:Q(n,6),experiment:O(n,7)}},window.dataLayer.push(c);else if(L(p,Ja,5))c=N(p,Ja,J(p,K,5)),window.dataLayer.push({originalUrlParameters:{dclid:O(c,1)||void 0,
gclid:O(c,2)||void 0,utmCampaign:O(c,3)||void 0,utmContent:O(c,4)||void 0,utmMedium:O(c,5)||void 0,utmSource:O(c,6)||void 0,utmTerm:O(c,7)||void 0}});else if(2===M(p,K)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"});n=document.getElementsByTagName("script")[0];l=document.createElement("script");l.async=!0;m=new Na(La,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");m=m instanceof Na&&m.constructor===Na&&m.h===Ma?m.s:"type_error:Const";
if(void 0===W)if(g=null,(h=k.trustedTypes)&&h.createPolicy){try{g=h.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(E){k.console&&k.console.error(E.message)}W=g}else W=g;m=(g=W)?g.createScriptURL(m):m;g=new Pa(m,Oa);m=l;m.src=g instanceof Pa&&g.constructor===Pa?g.h:"type_error:TrustedResourceUrl";(c=(g=null==(f=(c=(m.ownerDocument&&m.ownerDocument.defaultView||window).document).querySelector)?void 0:f.call(c,"script[nonce]"))?g.nonce||g.getAttribute("nonce")||"":"")&&
m.setAttribute("nonce",c);n.parentNode.insertBefore(l,n)}}};window.addEventListener("message",this.C)}D(a){this.h=this.s.get("_ga_devsite")||"";var b=new Ca;a=ta(b,1,a,!1);b=ta(a,2,this.h,"");a=new Da;F(a);null==b&&(b=void 0);F(a);var d=M(a,Ea);d&&2!==d&&null!=b&&H(a,d,void 0,!1);a=H(a,2,b);if(window.parent!==window){b=window.parent;d=b.postMessage;a:{la=!0;try{var e=JSON.stringify(a.toJSON(),za);break a}finally{la=!1}e=void 0}d.call(b,e,"*")}}}Ra.prototype.notifyIframeReady=Ra.prototype.D;
function Sa(a){const b={};for(const d of a){a=O(d,1);let e;O(d,J(d,T,2))?e=O(d,J(d,T,2)):Q(d,J(d,T,3))?e=Q(d,J(d,T,3)):4===M(d,T)&&(e=P(d,J(d,T,4))?"True":"False");b[a]=e}return b}
function Ua(a){const b={};if(!a)return b;b.hasProfile=P(a,6)?"True":"False";b.practitionerType=O(a,1)||"Property not set";b.profileCreationMethod=O(a,4)||"Property not set";b.profileHasInterests=P(a,12)?"True":"False";b.profileInterests=O(a,13)||"Property not set";b.profileHasJobTitle=P(a,10)?"True":"False";b.profileHasLocation=P(a,7)?"True":"False";b.profileHasPronoun=P(a,9)?"True":"False";b.profileIsPublic=P(a,8)?"True":"False";b.profileSocialLinks=O(a,11)||"Property not set";b.profileBadgeEmailOptIn=
P(a,5)?"True":"False";b.profileFeedbackEmailOptIn=P(a,2)?"True":"False";b.profileNewsletterEmailOptIn=P(a,3)?"True":"False";return b}function Ta(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var Va=Ra,X=["AnalyticsLibrary"],Y=k;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Va?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Va;}).call(this);
